### ISSUE TITLE
replicache-client: make failed http connections less dire

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#57]
From log output from replicache-client:

```
2020-05-11 23:05:29.895279-1000 Runner[44693:1863873] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Exception: Error invoking "beginSync": PlatformException(UNAVAILABLE, sync failed: Post "http://localhost:7001/pull": dial tcp [::1]:7001: connect: connection refused, null)
#0      Replicache._invoke (package:replicache/replicache.dart:397:7)
<asynchronous suspension>
#1      Replicache._beginSync (package:replicache/replicache.dart:243:35)
<asynchronous suspension>
#2      Replicache._sync (package:replicache/replicache.dart:237:28)
<asynchronous suspension>
#3      Replicache.sync (package:replicache/replicache.dart:346:13)
<asynchronous suspension>
#4      _rootRun (dart:async/zone.dart:1122:38)
#5      _CustomZone.run (dart:async/zone.dart:1023:19)
#6      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#8      _rootRun (dart:async/zone.dart:1126:13)
#9      _CustomZone.run (dart:async/zone.dart:1023:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

We are offline-first, this shouldn't look like such a big deal.

**Comment by aboodman** [comment]
Probably just a matter of removing the stack.

**Comment by phritz** [comment]
if it arises in repc we can open a new issue
